package pers.wyj.smartteaching.model;

import javax.persistence.*;
import java.io.Serializable;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import java.util.Date;

/**
 * @Description  Generated by groovy script
 * @Author  wuyangjun
 * @Date 2019-12-23 
 */

@Setter
@Getter
@ToString
@Entity
@Table ( name ="class_homework" )
public class ClassHomeworkEntity  implements Serializable {

	private static final long serialVersionUID =  334455418214703767L;

	/**
	 * 唯一id
	 */
   	@Column(name = "id" )
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * 班级id

	 */
   	@Column(name = "class_id" )
	private Long classId;

	/**
	 * 作业id
	 */
   	@Column(name = "homework_id" )
	private Long homeworkId;

	/**
	 * 作业提交截止时间
	 */
   	@Column(name = "homework_deadline_time" )
	private Date homeworkDeadlineTime;

	/**
	 * 作业发布时间
	 */
   	@Column(name = "homework_post_time" )
	private Date homeworkPostTime;

	/**
	 * 作业开始时间
	 */
   	@Column(name = "homework_start_time" )
	private Date homeworkStartTime;

}
