package pers.wyj.smartteaching.model;

import javax.persistence.*;
import java.io.Serializable;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import java.util.Date;

/**
 * @Description  Generated by groovy script
 * @Author  wuyangjun
 * @Date 2019-11-27 
 */

@Setter
@Getter
@ToString
@Entity
@Table ( name ="classes" )
public class ClassesEntity  implements Serializable {

	private static final long serialVersionUID =  1907195230583765483L;

	/**
	 * 班级唯一ID
	 */
   	@Column(name = "id" )
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * 班级状态
	 */
   	@Column(name = "class_status" )
	private Long classStatus;

	/**
	 * 班级名称
	 */
   	@Column(name = "class_name" )
	private String className;

	/**
	 * 班级类型
	 */
   	@Column(name = "class_type" )
	private String classType;

	/**
	 * 班级创建时间
	 */
   	@Column(name = "class_create_time" )
	private Date classCreateTime;

	/**
	 * 班级邀请码
	 */
   	@Column(name = "class_invite_code" )
	private String classInviteCode;

	/**
	 * 教师ID
	 */
   	@Column(name = "teacher_id" )
	private Long teacherId;

}
