package pers.wyj.smartteaching.model;

import javax.persistence.*;
import java.io.Serializable;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import java.util.Date;

/**
 * @Description  Generated by groovy script
 * @Author  wuyangjun
 * @Date 2019-12-22 
 */

@Setter
@Getter
@ToString
@Entity
@Table ( name ="homework" )
public class HomeworkEntity  implements Serializable {

	private static final long serialVersionUID =  1787331291568212622L;

	/**
	 * 作业唯一ID
	 */
   	@Column(name = "id" )
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * 作业支持上传的文件格式
	 */
   	@Column(name = "homework_format" )
	private String homeworkFormat;

	/**
	 * 文件id
	 */
   	@Column(name = "file_id" )
	private Long fileId;

	/**
	 * 作业标题

	 */
   	@Column(name = "homework_title" )
	private String homeworkTitle;

	/**
	 * 作业发布创建日期

	 */
   	@Column(name = "homework_create_time" )
	private Date homeworkCreateTime;

	/**
	 * 作业描述
	 */
   	@Column(name = "homework_description" )
	private String homeworkDescription;

	/**
	 * 教师id
	 */
   	@Column(name = "teacher_id" )
	private Long teacherId;

}
