package pers.wyj.smartteaching.model;

import javax.persistence.*;
import java.io.Serializable;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * @Description  Generated by groovy script
 * @Author  wuyangjun
 * @Date 2019-11-27 
 */

@Setter
@Getter
@ToString
@Entity
@Table ( name ="homework" )
public class HomeworkEntity  implements Serializable {

	private static final long serialVersionUID =  5642868855000304420L;

	/**
	 * 作业唯一ID
	 */
   	@Column(name = "id" )
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * 作业支持上传的文件格式
	 */
   	@Column(name = "homework_format" )
	private String homeworkFormat;

	/**
	 * 文件id
	 */
   	@Column(name = "file_id" )
	private Long fileId;

	/**
	 * 可见班级ID
	 */
   	@Column(name = "class_id" )
	private Long classId;

}
