package pers.wyj.smartteaching.model;

import javax.persistence.*;
import java.io.Serializable;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import java.util.Date;

/**
 * @Description  Generated by groovy script
 * @Author  wuyangjun
 * @Date 2019-11-27 
 */

@Setter
@Getter
@ToString
@Entity
@Table ( name ="question" )
public class QuestionEntity  implements Serializable {

	private static final long serialVersionUID =  1440426050731573656L;

	/**
	 * 题目（问题）唯一ID
	 */
   	@Column(name = "id" )
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * 题目状态
	 */
   	@Column(name = "status" )
	private String status;

	/**
	 * 所属题库ID
	 */
   	@Column(name = "question_bank_id" )
	private Long questionBankId;

	/**
	 * 创建时间
	 */
   	@Column(name = "create_time" )
	private Date createTime;

	/**
	 * 问题类型
	 */
   	@Column(name = "question_type" )
	private Integer questionType;

	/**
	 * 问题标签
	 */
   	@Column(name = "tags" )
	private String tags;

	/**
	 * 问题描述
	 */
   	@Column(name = "description" )
	private String description;

	/**
	 * 问题选项
	 */
   	@Column(name = "options" )
	private String options;

	/**
	 * 问题答案
	 */
   	@Column(name = "answer" )
	private String answer;

	/**
	 * 问题解析
	 */
   	@Column(name = "analysis" )
	private String analysis;

}
