package pers.wyj.smartteaching.model;

import javax.persistence.*;
import java.io.Serializable;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import java.util.Date;

/**
 * @Description  Generated by groovy script
 * @Author  wuyangjun
 * @Date 2019-11-27 
 */

@Setter
@Getter
@ToString
@Entity
@Table ( name ="question_bank" )
public class QuestionBankEntity  implements Serializable {

	private static final long serialVersionUID =  2797549679724433318L;

	/**
	 * 题库唯一ID
	 */
   	@Column(name = "id" )
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * 题库状态
	 */
   	@Column(name = "status" )
	private String status;

	/**
	 * 题库名称
	 */
   	@Column(name = "question_name" )
	private String questionName;

	/**
	 * 创建的教师
	 */
   	@Column(name = "teacher_id" )
	private Long teacherId;

	/**
	 * 创建时间
	 */
   	@Column(name = "create_time" )
	private Date createTime;

	/**
	 * 题库标签
	 */
   	@Column(name = "tags" )
	private String tags;

}
