package pers.wyj.smartteaching.model;

import javax.persistence.*;
import java.io.Serializable;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import pers.wyj.smartteaching.common.AccountStatus;
import pers.wyj.smartteaching.common.AccountType;

/**
 * @Description  Generated by groovy script
 * @Author  wuyangjun
 * @Date 2019-11-28 
 */

@Setter
@Getter
@ToString
@Entity
@Table ( name ="user" )
public class UserEntity  implements Serializable {

	private static final long serialVersionUID =  4572259439054777514L;

	/**
	 * 用户唯一ID
	 */
   	@Column(name = "id" )
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * 用户名字
	 */
   	@Column(name = "user_name" )
	private String userName;

	/**
	 * 用户性别：0：男，1：女
	 */
   	@Column(name = "user_gender" )
	private Integer userGender;

	/**
	 * 学号（工号）
	 */
   	@Column(name = "user_unique_id" )
	private String userUniqueId;

	/**
	 * 用户邮箱
	 */
   	@Column(name = "user_mail" )
	private String userMail;

	/**
	 * 用户手机号
	 */
   	@Column(name = "user_phone" )
	private String userPhone;

	/**
	 * 账户名
	 */
   	@Column(name = "account_name" )
	private String accountName;

	/**
	 * 账户密码
	 */
   	@Column(name = "account_password" )
	private String accountPassword;

	/**
	 * 账户类型（0：学生，1：教师）
	 */
   	@Column(name = "account_type" )
	@Enumerated(value = EnumType.ORDINAL)
	private AccountType accountType;

	/**
	 * 账户状态（登录、冻结、删除）
	 * @Enumerated自动将其以数字ordinal形式映射到数据表
	 */
   	@Column(name = "account_status" )
	@Enumerated(value = EnumType.ORDINAL)
	private AccountStatus accountStatus;

}
